# Generated by Django 5.0.4 on 2024-05-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='pret',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='etat',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('emprunte', 'emprunte'), ('a enlever', 'a enlever')], max_length=50, null=True),
        ),
    ]
