# Generated by Django 5.0.4 on 2024-05-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_livre_pret_alter_exemplaire_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprunt',
            name='confirmer_retour',
            field=models.BooleanField(default=False),
        ),
    ]
